# Generated by Django 6.0.5 on 2026-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
